name: CI

on:
  push:
    branches: [main]
  pull_request:
  # Run every Monday at 00:00 UTC.
  schedule:
    - cron: 0 0 * * MON

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          cache: pip
          cache-dependency-path: ".pre-commit-config.yaml"
      - uses: pre-commit/action@v2.0.3
        with:
          extra_args: --all-files

  tests:
    name: tests / ${{ matrix.python }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    needs: [pre-commit]
    env:
      PYTHONIOENCODING: utf-8

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
        python: ["3.7", "3.8", "3.9", "3.10"]

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          cache-dependency-path: "pyproject.toml"

      - name: Install base requirements
        run: |
          python -m pip install pip wheel --upgrade
          python -m pip install nox

      - name: Run nox tests session (latest PyPI black)
        run: nox --force-color --verbose -s tests-${{ matrix.python }} -- --color=yes -v --durations 10

      - name: Run nox tests session (main black)
        run: >
          nox --force-color --verbose -s tests-${{ matrix.python }} --reuse-existing-virtualenvs
          -- --black-req git+https://github.com/psf/black.git --color=yes -v --durations 10
